### ISSUE TITLE
Can not find Qt5ScxmlConfig.cmake when building

### ISSUE THREAD

**Issue by ghost** [swri-robotics/ros_scxml#26]
Hey,

when I want to build the project with colcon build I get the following error:

`Starting >>> tesseract_collision
--- stderr: scxml_core                                                                                                                                                                 
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Scxml" with any
  of the following names:

    Qt5ScxmlConfig.cmake
    qt5scxml-config.cmake

  Add the installation prefix of "Qt5Scxml" to CMAKE_PREFIX_PATH or set
  "Qt5Scxml_DIR" to a directory containing one of the above files.  If
  "Qt5Scxml" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)

---
Failed   <<< scxml_core [0.15s, exited with code 1]
`

Someone has an Idea where I could find the Qt5ScxmlConfig.cmake file?

Thanks for your help!
Johannes

**Comment by Drojas251** [comment]
Same issue

**Comment by marip8** [comment]
If you're using the Qt 5.12+ build from the PPA referenced in the README, all of the files are stored in the `/opt/qt5xx` folder. The CMake config file for the Scxml module should be located in the `opt/qt5xx/lib/cmake/Qt5Scxml` directory. The `/opt` directory is not a standard CMake search path, so you need to update the `CMAKE_PREFIX_PATH` variable of your build environment to include the `/opt/qt5xx/lib/cmake` directory. Check out [this section of the README](https://github.com/swri-robotics/ros_scxml#setup-environment-variables) for more details

**Comment by Drojas251** [comment]
@marip8 Yes I have ran these commands 

export CMAKE_PREFIX_PATH=/opt/qt513/lib/cmake:$CMAKE_PREFIX_PATH
export LD_LIBRARY_PATH=/opt/qt513/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/qt513/plugins:$LD_LIBRARY_PATH

and even added them to my bashrc. 

When running echo $CMAKE_PREFIX_PATH, I get this output 
/opt/qt513/lib/cmake: 

However I still get the same error when building the workspace. 

Any Idea why this is?

**Comment by marip8** [comment]
Are you building in the same terminal where you've set these environment variables? I personally use the Qt Creator IDE which maintains its own variables for the build environment; in this case, I actually had to modify those environment variables in the IDE rather than a terminal/.bashrc

**Comment by marip8** [comment]
Closing; addressed in #30. This should be much easier now that we are not using custom installs of Qt
