### ISSUE TITLE
Bug in GetCurrentState

### ISSUE THREAD

**Issue by KevinWarburton** [swri-robotics/ros_scxml#27]
@marip8 and I found the following issue: The following line produces a SIGABRT because the `sm_info_->configuration()` call occasionally returns an empty vector of state IDs:

https://github.com/swri-robotics/ros_scxml/blob/597560b8d150cfb1a3df1a7c329b8bfd8be7c528/scxml_core/src/state_machine.cpp#L724

Since the `QScxmlStateMachineInfo` class is defined in a private Qt header which is not documented, it is unclear what this class does or why this object returns an empty vector in the first place.

In our use case, we encountered this error when calling `getCurrentState` at relatively high frequency as the state machine is transitioning. Is it possible that the state becomes undefined during a transition? If so, we should put some sort of lock around the Qt internal objects until the state becomes defined again.

**Comment by marip8** [comment]
Closing; addressed in #30
