### ISSUE TITLE
CI for ROS 1 Repositories

### ISSUE THREAD

**Issue by marip8** [swri-robotics/ros_scxml#9]
What is the correct way to build this package in CI for a ROS 1 repository that depends on this repository? Currently I get errors because the `rosdep` keys for the ROS2 dependencies of the `rclcpp_scxml_demos` package cannot be resolved. I see in the CI file we only provide CI for ROS2 and ignore the ROS1 dependencies (`catkin` and `roscpp`). Is this the right approach when implementing CI for ROS1? It seems a bit hacky, and I'm not sure if there is a better way (i.e. CATKIN_IGNORE in ROS2 packages, etc.).

Sidenote: we should provide CI for ROS1 since we advertise the ability to use this repository in ROS 1

**Comment by jrgnicho** [comment]
Definitely on board with this request.   I think the rosdep problem can be solved using by setting the  `ROSDEP_SKIP_KEYS` as done [here](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/master/.github/workflows/main.yml)

**Comment by marip8** [comment]
Closing; addressed by #30
